### PR TITLE
Fix opensearch version to use for plugin

### PR DESCRIPTION
**Pull request by jayeshathila**
### Description
Logstash-input-opensearch plugin was failing in load stage.

### Issues Resolved
NA

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VijayanB** [comment]
Will migrate to opensearch-ruby once we set up CI

**Comment by naveentatikonda** [comment]
The plugin code which I tried to load into logstash already has this change but still it is unable to load the plugin for me.

**Comment by jayeshathila** [comment]
> The plugin code which I tried to load into logstash already has this change but still it is unable to load the plugin for me.

Worked with Naveen on making this work (Tested for `http`) .

**Comment by naveentatikonda** [comment]
Added this fix as part of some other PR. So, closing it.

**Pull request closed without merging**
